### ISSUE TITLE
help

### ISSUE THREAD

**Issue by antonw-25** [infinet/xt_wgobfs#10]
Not sure how to install - https://github.com/WeeJeWel/wg-easy
DO I just put the eserver side ip stuff for wg_pre_up? I know nothing. Thanks

**Comment by infinet** [comment]
I am not familiar with wg-easy, here is just my guess.

Take a look at https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole , you can create a similar docker-compose.yml, in its environment section, add one line:

- WG_PRE_UP: "iptables -t mangle -I INPUT -p udp -m udp --dport 6789 -j WGOBFS --key mysecretkey --unobfs; iptables -t mangle -I OUTPUT -p udp -m udp --sport 6789 -j WGOBFS --key mysecretkey --obfs"

Replace 6789 with your server's port.

**Comment by antonw-25** [comment]
Hi, im extremely sorry - I linked the wrong one, this is the one I meant to link:https://github.com/notthebee/ansible-easy-vpn
Thanks so much for such a quick and helpful reply though!

**Comment by infinet** [comment]
If you cannot make it work with ansible-easy-vpn, may I suggest go directly with iptables?
