### ISSUE TITLE
openwrt snapshot issue

### ISSUE THREAD

**Issue by fox85** [infinet/xt_wgobfs#12]
Hi, just installed a fresh openwrt snapshot

OpenWrt SNAPSHOT r22217-dc0de05e10 / LuCI Master git-23.039.28596-41e9b8d

Linux WRT32X 5.15.98 #0 SMP Sat Mar 4 20:27:30 2023 armv7l GNU/Linux

after compiled and installed the ipk, issue a command, then got an error:

root@WRT32X:~# iptables -t mangle -I INPUT -p udp -m udp --sport 6789 -j WGOBFS --key mysecretkey --unobfs
iptables v1.8.8 (nf_tables): unknown option "--key"
Try `iptables -h' or 'iptables --help' for more information.

Don't know why, the patch works very well on openwrt 22.03

**Comment by fox85** [comment]
even I manually issued insmod , still got the same error:

root@WRT32X:~# insmod /lib/modules/5.15.98/xt_WGOBFS.ko
module is already loaded - xt_WGOBFS
root@WRT32X:~# iptables -t mangle -I INPUT -p udp -m udp --sport 6789 -j WGOBFS --key mysecretkey --unobfs
iptables v1.8.8 (nf_tables): unknown option "--key"
Try `iptables -h' or 'iptables --help' for more information.

**Comment by fox85** [comment]
nerver mind

**Comment by iGr33k** [comment]
Hi, @fox85 

Could you explain what was the issue, please?

**Comment by fox85** [comment]
> Hi, @fox85
> 
> Could you explain what was the issue, please?

Hi. I think it should be my problem. Thanks for your great patch, brother  👍
