### ISSUE TITLE
Andriod, IOS and windows client configuration

### ISSUE THREAD

**Issue by sinash14** [infinet/xt_wgobfs#14]
Hi,

Thanks for sharing your knowledge and hard work. 

Just wondering if I need to do anything at client side ? 

Thanks

**Comment by infinet** [comment]
It won't work directly on these system.

One possible solution is use a relay. See https://github.com/infinet/xt_wgobfs/issues/7.

**Comment by manchelsi** [comment]
How it works? The relay is established between the client and the server? How should the server and client be configured in this case? And what kind of traffic passes between the client and the relay?

**Comment by infinet** [comment]
Assuming using wireguard on mobile phone:

- On mobile phone, one can setup the relay as wireguard server
- Configure relay as in #7. It will obfuscate/unobfuscate WG when forwarding traffic between mobile phone and the real server.
- On server, configure the same obfuscate key, and use ip/port of relay as peer.

Client  <== Original WG ==>  Relay <== Obfuscated WG ==> Server

**Comment by infinet** [comment]
https://github.com/infinet/rs-wgobfs is cross-platform, works on Windows.
