### ISSUE TITLE
iptables v1.8.9 (nf_tables): unknown option "--key"

### ISSUE THREAD

**Issue by Mincubus** [infinet/xt_wgobfs#18]
I did the commands as written, but an error appeared. Debian 12

**Comment by infinet** [comment]
Has the kernel module been loaded? What is the output of `lsmod | grep WGOBFS`?

**Comment by lirigorm** [comment]
Hi, i use openwrt, but i have the same problem.
output of `lsmod | grep WGOBFS`:

> x_tables               24576 15 nft_compat,iptable_mangle,iptable_filter,ipt_REJECT,ip_tables,xt_time,xt_tcpudp,xt_multiport,xt_mark,xt_mac,xt_limit,xt_comment,xt_WGOBFS,xt_TCPMSS,xt_LOG
> xt_WGOBFS              12288  0

**Comment by romanrm** [comment]
It looks like you may have forgotten to put libxt_WGOBFS into the correct place. On my system it is at /usr/lib/x86_64-linux-gnu/xtables/libxt_WGOBFS.so. Adjust for your distro accordingly. Easiest is to run "find / | grep libxt_" and that way to determine where other iptables libs live. This additional one needs to be at the same location.

**Comment by infinet** [comment]
I agree with @romanrm, perhaps `libxt_WGOBFS.so` is missing. On Debian 12,
`make install` shall copy `libxt_WGOBFS.so` to the correct location. Also please make sure the kernel module is loaded.

On OpenWrt, the build generates two pakcages, `kmod-ipt-wgobfs_xxx.ipk` and `iptables-mod-wgobfs_xxx.ipk`. Double check both are installed. The latest OpenWrt I tested was 22.03.3.

**Comment by infinet** [comment]
Error messages such as `unknown option "--key"`, `unknown option "--obfs"`, `unknown option "--unobfs"` happens when the kernel module is not loaded, or `libxt_WGOBFS.so` is missing.

I've only tested it up to OpenWrt 22.03. If you're on 23.05 or later, I'm afraid I might not be able to help you directly.

**Comment by lirigorm** [comment]
I tried it on version 22.03.5. Works. But how to make it work on version 23.05? I did everything the same as on 22.03.5, but it does not work.

**Comment by infinet** [comment]
It may be related a bug that was fixed by #15. I have packaged a new version. Please try the latest openwrt/package/Makefile.

**Comment by lirigorm** [comment]
I tested the new version. It works on openwrt 23.05.

**Comment by infinet** [comment]
Great! Glad it works. I am closing this issue.

**Comment by lirigorm** [comment]
Thanks @infinet !
