### ISSUE TITLE
Multiple clients with different circumvention levels

### ISSUE THREAD

**Issue by boss1819** [infinet/xt_wgobfs#21]
Hi,

if you have 2 clients, client A behind the firewall and need to use xt_wgobfs to connect to the server, client B connects from a loaction where wireguard connection from client to server is not blocked. 

what should be the iptables configuration on the server, to selectively apply obfs and unobfs only to traffic from client A?
any smart iptable rule that can do, assuming client IP address is not static?

if server has iptables configured as described in readme, but client B does not use xt_wgobfs, will the traffic be dropped?

thanks and regards

**Comment by infinet** [comment]
It is tricky to do it with iptables along. Better set up two wg listen on separated ports. Then apply iptables rules to the port serves client A.
