### ISSUE TITLE
Cant establish connection between little endian and big endian devices.

### ISSUE THREAD

**Issue by alexburt** [infinet/xt_wgobfs#8]
I cant establish connection between my Openwrt router and Linux PC.
Problem is in operations like "chacha_input = *p64 + 42;" which will give a different result on a different machines.
https://github.com/infinet/xt_wgobfs/blob/main/src/xt_WGOBFS_main.c#L48

Very good project. Thank you!
patch:
[wgobfs_big_endian.txt](https://github.com/infinet/xt_wgobfs/files/10835818/wgobfs_big_endian.txt)

**Comment by infinet** [comment]
Thank you so much!

Fixed in https://github.com/infinet/xt_wgobfs/commit/d246f3f85bbbf90f64dbe47c256e8189bd0992e0.

**Comment by alexburt** [comment]
cpu_to_le64(var) + 42 is not equal to cpu_to_le64(var+42)

**Comment by infinet** [comment]
You are right, they are not the same. However, here it is used to generate pseudo-random bytes for padding. Its peer does not need to regenerate the same pseudo-random bytes.

**Comment by alexburt** [comment]
thank you!
