### ISSUE TITLE
Cant compile v4 for openwrt.

### ISSUE THREAD

**Issue by alexburt** [infinet/xt_wgobfs#9]
I cant compile for openwrt anymore. Make V=s stops with strange "Error 2" w/o explanation because of missed autogen results.

make[3]: Entering directory '/tmp/wrt/openwrt/feeds/packages/net/xt_wgobfs'
checking for library containing putmsg... SHELL= flock /tmp/wrt/openwrt/tmp/.xt_wgobfs-0.4.tar.xz.flock -c '    /tmp/wrt/openwrt/scripts/download.pl "/tmp/wrt/openwrt/dl" "xt_wgobfs-0.4.tar.xz" "59e89d904035bb51d9c2efc96957f13bb95a75fc532a20e059d916aa2d4d56da" "" "https://github.com/infinet/xt_wgobfs/releases/download/v0.4/"    '
rm -f /tmp/wrt/openwrt/build_dir/target-mips_24kc_musl/xt_wgobfs-0.4/.built
touch /tmp/wrt/openwrt/build_dir/target-mips_24kc_musl/xt_wgobfs-0.4/.built_check
make --jobserver-auth=3,4  -C /tmp/wrt/openwrt/build_dir/target-mips_24kc_musl/xt_wgobfs-0.4 ARCH="mips" CROSS_COMPILE="mips-openwrt-linux-musl-" DESTDIR="/tmp/wrt/openwrt/build_dir/target-mips_24kc_musl/xt_wgobfs-0.4/ipkg-install" DEPMOD="/bin/true" all
make[4]: Entering directory '/tmp/wrt/openwrt/build_dir/target-mips_24kc_musl/xt_wgobfs-0.4'
make[4]: Leaving directory '/tmp/wrt/openwrt/build_dir/target-mips_24kc_musl/xt_wgobfs-0.4'
make[3]: *** [Makefile:91: /tmp/wrt/openwrt/build_dir/target-mips_24kc_musl/xt_wgobfs-0.4/.built] Error 2
make[3]: Leaving directory '/tmp/wrt/openwrt/feeds/packages/net/xt_wgobfs'
time: package/feeds/packages/xt_wgobfs/compile#0.19#0.04#1.44
make[2]: *** [package/Makefile:113: package/feeds/packages/xt_wgobfs/compile] Error 2

There is many files missed in v4 in compare to v3. v4 is just a repo.
Also tarball contains old openwrt/Makefile.

tar tvf xt_wgobfs-0.4.tar.xz 
drwxr-xr-x wei/wei           0 2023-03-01 16:57 xt_wgobfs-0.4/
drwxr-xr-x wei/wei           0 2023-03-01 16:57 xt_wgobfs-0.4/openwrt/
drwxr-xr-x wei/wei           0 2023-03-01 16:57 xt_wgobfs-0.4/openwrt/package/
-rw-r--r-- wei/wei        2314 2023-03-01 16:57 xt_wgobfs-0.4/openwrt/package/Makefile
-rw-r--r-- wei/wei         862 2023-03-01 16:57 xt_wgobfs-0.4/openwrt/package/README.md
-rw-r--r-- wei/wei        1536 2023-03-01 16:57 xt_wgobfs-0.4/configure.ac
-rw-r--r-- wei/wei        1197 2023-03-01 16:57 xt_wgobfs-0.4/Makefile.am
drwxr-xr-x wei/wei           0 2023-03-01 16:57 xt_wgobfs-0.4/src/
-rw-r--r-- wei/wei       13577 2023-03-01 16:57 xt_wgobfs-0.4/src/xt_WGOBFS_main.c
-rw-r--r-- wei/wei         741 2023-03-01 16:57 xt_wgobfs-0.4/src/chacha8.h
-rw-r--r-- wei/wei        2851 2023-03-01 16:57 xt_wgobfs-0.4/src/wg.h
-rw-r--r-- wei/wei          67 2023-03-01 16:57 xt_wgobfs-0.4/src/Kbuild
-rw-r--r-- wei/wei        4308 2023-03-01 16:57 xt_wgobfs-0.4/src/libxt_WGOBFS.c
-rw-r--r-- wei/wei        2814 2023-03-01 16:57 xt_wgobfs-0.4/src/chacha8.c
-rw-r--r-- wei/wei         337 2023-03-01 16:57 xt_wgobfs-0.4/src/xt_WGOBFS.h
-rwxr-xr-x wei/wei          53 2023-03-01 16:57 xt_wgobfs-0.4/autogen.sh
-rw-r--r-- wei/wei       18092 2023-03-01 16:57 xt_wgobfs-0.4/LICENSE
-rw-r--r-- wei/wei        2485 2023-03-01 16:57 xt_wgobfs-0.4/README.md
-rw-r--r-- wei/wei         777 2023-03-01 16:57 xt_wgobfs-0.4/Makefile.libxt.in

tar tvf 1/xt_wgobfs-0.3.tar.xz 
drwxr-xr-x root/root         0 2022-11-24 14:01 xt_wgobfs-0.3/
-rw-r--r-- root/root     18092 2022-11-24 13:58 xt_wgobfs-0.3/LICENSE
-rw-r--r-- root/root      1197 2022-11-24 13:58 xt_wgobfs-0.3/Makefile.am
-rw-r--r-- root/root       777 2022-11-24 13:58 xt_wgobfs-0.3/Makefile.libxt.in
-rw-r--r-- root/root      2118 2022-11-24 13:58 xt_wgobfs-0.3/README.md
-rwxr-xr-x root/root        53 2022-11-24 13:58 xt_wgobfs-0.3/autogen.sh
-rw-r--r-- root/root      1535 2022-11-24 13:58 xt_wgobfs-0.3/configure.ac
drwxr-xr-x root/root         0 2022-11-24 13:58 xt_wgobfs-0.3/src/
-rw-r--r-- root/root        67 2022-11-24 13:58 xt_wgobfs-0.3/src/Kbuild
-rw-r--r-- root/root      2734 2022-11-24 13:58 xt_wgobfs-0.3/src/chacha8.c
-rw-r--r-- root/root       741 2022-11-24 13:58 xt_wgobfs-0.3/src/chacha8.h
-rw-r--r-- root/root      4308 2022-11-24 13:58 xt_wgobfs-0.3/src/libxt_WGOBFS.c
-rw-r--r-- root/root      2851 2022-11-24 13:58 xt_wgobfs-0.3/src/wg.h
-rw-r--r-- root/root       337 2022-11-24 13:58 xt_wgobfs-0.3/src/xt_WGOBFS.h
-rw-r--r-- root/root     13577 2022-11-24 13:58 xt_wgobfs-0.3/src/xt_WGOBFS_main.c
drwxr-xr-x root/root         0 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/
-rw-r--r-- root/root    327114 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/ltmain.sh
-rwxr-xr-x root/root      5827 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/ar-lib
-rwxr-xr-x root/root      7383 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/compile
-rwxr-xr-x root/root     44283 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/config.guess
-rwxr-xr-x root/root     36136 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/config.sub
-rwxr-xr-x root/root     15368 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/install-sh
-rwxr-xr-x root/root      6878 2022-11-24 14:01 xt_wgobfs-0.3/build-aux/missing
drwxr-xr-x root/root         0 2022-11-24 14:01 xt_wgobfs-0.3/m4/
-rw-r--r-- root/root    306432 2022-11-24 14:01 xt_wgobfs-0.3/m4/libtool.m4
-rw-r--r-- root/root     14514 2022-11-24 14:01 xt_wgobfs-0.3/m4/ltoptions.m4
-rw-r--r-- root/root      4384 2022-11-24 14:01 xt_wgobfs-0.3/m4/ltsugar.m4
-rw-r--r-- root/root       699 2022-11-24 14:01 xt_wgobfs-0.3/m4/ltversion.m4
-rw-r--r-- root/root      6140 2022-11-24 14:01 xt_wgobfs-0.3/m4/lt~obsolete.m4
-rw-r--r-- root/root     54272 2022-11-24 14:01 xt_wgobfs-0.3/aclocal.m4
-rwxr-xr-x root/root    442848 2022-11-24 14:01 xt_wgobfs-0.3/configure
-rw-r--r-- root/root      1727 2022-11-24 14:01 xt_wgobfs-0.3/config.h.in
-rw-r--r-- root/root     22954 2022-11-24 14:01 xt_wgobfs-0.3/Makefile.in

**Comment by infinet** [comment]
Please try the new release.

**Comment by alexburt** [comment]
works. Thank you!
